# Generated by Django 4.2.15 on 2024-08-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='uploads/profile_photo')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('xabar_text', models.TextField(max_length=300)),
                ('kim_yozdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jonatdi', to='UserApp.foydalanuvchilar')),
                ('kimga_yozdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_qildi', to='UserApp.foydalanuvchilar')),
            ],
        ),
    ]
